language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

cache:
  directories:
    - $HOME/.composer

env:
  - SYMFONY_DISPATCHER_VERSION=2.8.*
  - SYMFONY_DISPATCHER_VERSION=3.4.*
  - SYMFONY_DISPATCHER_VERSION=4.0.*
  - SYMFONY_DISPATCHER_VERSION=4.1.*
  - SYMFONY_DISPATCHER_VERSION=4.2.*
  - SYMFONY_DISPATCHER_VERSION=4.3.*
  - SYMFONY_DISPATCHER_VERSION=4.4.*
  - SYMFONY_DISPATCHER_VERSION=5.0.*
  - SYMFONY_DISPATCHER_VERSION=5.1.*

matrix:
  exclude:
    - php: 7.1
      env: SYMFONY_DISPATCHER_VERSION=5.0.*
    - php: 7.1
      env: SYMFONY_DISPATCHER_VERSION=5.1.*

before_script:
    - composer self-update
    - if [ "$SYMFONY_DISPATCHER_VERSION" != "" ]; then composer require "symfony/event-dispatcher:${SYMFONY_DISPATCHER_VERSION}" --no-update; fi;
    - composer update

script:
    - vendor/bin/phpunit
