name: CI
on: [pull_request]
jobs:
  tests:
    name: NodalFlow (PHP ${{ matrix.php-versions }} / dispatcher ${{ matrix.dispatcher-versions }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
        dispatcher-versions: ['3.4.*', '4.0.*', '4.1.*', '4.2.*', '4.3.*', '4.4.*', '5.0.*', '5.1.*', '5.2.*', '5.3.*', '5.4.*', '6.0.*', '6.1.*']
        exclude:
          - php-versions: 7.2
            dispatcher-versions: 6.0.*
          - php-versions: 7.2
            dispatcher-versions: 6.1.*
          - php-versions: 7.3
            dispatcher-versions: 6.0.*
          - php-versions: 7.3
            dispatcher-versions: 6.1.*
          - php-versions: 7.4
            dispatcher-versions: 6.0.*
          - php-versions: 7.4
            dispatcher-versions: 6.1.*
          - php-versions: 8.0
            dispatcher-versions: 3.4.*
          - php-versions: 8.0
            dispatcher-versions: 4.0.*
          - php-versions: 8.0
            dispatcher-versions: 4.1.*
          - php-versions: 8.0
            dispatcher-versions: 4.2.*
          - php-versions: 8.0
            dispatcher-versions: 4.3.*
          - php-versions: 8.0
            dispatcher-versions: 6.1.*
          - php-versions: 8.1
            dispatcher-versions: 3.4.*
          - php-versions: 8.1
            dispatcher-versions: 4.0.*
          - php-versions: 8.1
            dispatcher-versions: 4.1.*
          - php-versions: 8.1
            dispatcher-versions: 4.2.*
          - php-versions: 8.1
            dispatcher-versions: 4.3.*

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, gmp, bcmath

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Remove composer.lock
        run: rm -f composer.lock

      - name: Install Symfony dispatcher ${{ matrix.dispatcher-versions }}
        run: composer require "symfony/event-dispatcher:${{ matrix.dispatcher-versions }}" --dev --no-update

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Test with phpunit
        run: vendor/bin/phpunit
